In [1]:
import numpy as np
from GridWorld import env

In [2]:
def policy_eval(policy, discount_factor = 0.999, theta = 0.00000001):
  # Value function initialized to 0 for all states
  val_func = np.zeros(num_states)
  while True:
    delta = 0
    # For each state in the state-space
    for curr_state in range(num_states):
      # New value for each state
      updated_val = 0
      # For each of the possible actions in the current state
      # action_prob: Probability of taking curr_action in curr_state
      for curr_action, action_prob in enumerate(policy[curr_state]):
        # prob: State Transition Probability
        # reward, next_state: Immediate reward and next state on taking curr_action in curr_state
        # isdone: Whether the next state is Terminal or not
        prob, next_state, reward, isdone = env(curr_state, curr_action, rows, columns)
        # Bellman Expectation equation
        updated_val += action_prob * prob * (reward + discount_factor * val_func[next_state])
      # delta: absolute change in the values
      delta = max(delta, np.abs(updated_val - val_func[curr_state]))
      val_func[curr_state] = updated_val
    if delta < theta:
      break
  return val_func

In [7]:
num_actions = 4
rows = 4
columns = 4
num_states = rows * columns
# Uniform Random Policy
policy = np.ones([num_states, num_actions])/num_actions 
val_func = policy_eval(policy = policy)
print(f'Value Function:\n {val_func.reshape(rows, columns)}')

Value Function:
 [[  0.         -12.77500171 -18.66692937 -20.62763479]
 [-12.77500171 -16.70622395 -18.66889008 -18.66692938]
 [-18.66692937 -18.66889008 -16.70622395 -12.77500172]
 [-20.62763479 -18.66692938 -12.77500172   0.        ]]
