In [1]:
import numpy as np
from GridWorld import env

In [2]:
def policy_eval(policy, discount_factor, theta = 0.00000001):
  # Value function initialized to 0 for all states
  val_func = np.zeros(num_states)
  while True:
    delta = 0
    # For each state in the state-space
    for curr_state in range(num_states):
      # New value for each state
      updated_val = 0
      # For each of the possible actions in the current state
      # action_prob: Probability of taking curr_action in curr_state
      for curr_action, action_prob in enumerate(policy[curr_state]):
        # prob: State Transition Probability
        # reward, next_state: Immediate reward and next state on taking curr_action in curr_state
        # isdone: Whether the next state is Terminal or not
        prob, next_state, reward, isdone = env(curr_state, curr_action, rows, columns)
        # Bellman Expectation equation
        updated_val += action_prob * prob * (reward + discount_factor * val_func[next_state])
      # delta: absolute change in the values
      delta = max(delta, np.abs(updated_val - val_func[curr_state]))
      val_func[curr_state] = updated_val
    if delta < theta:
      break
  return val_func

In [3]:
def policy_improve(policy, discount_factor = 0.999):
  # Current policy assumed to be best initially
  policy_stable = True
  # Evaluate the current policy to get Value function for that policy
  val_func = policy_eval(policy, discount_factor)
  # For each state in state-space
  for curr_state in range(num_states):
    # The action that would be picked with most probability under the current policy
    curr_action = np.argmax(policy[curr_state])
    A = np.zeros(num_actions)
    # For each action available in the current state
    for action in range(num_actions):
      # prob: State Transition Probability
      # reward, next_state: Immediate reward and next state on taking curr_action in curr_state
      # isdone: Whether the next state is Terminal or not
      prob, next_state, reward, isdone = env(curr_state, action, rows, columns)
      A[action] = prob * (reward + discount_factor * val_func[next_state])
    # Bellman Optimality equation (Action taken Greedily)
    best_action = np.argmax(A)
    # Update the policy
    policy[curr_state] = np.eye(num_actions)[best_action]
    # Check if the Action taken under new policy is same as the old policy
    if(best_action != curr_action):
      # Turn policy_stable off if both are not same
      policy_stable = False
  # Current poloicy is an Optimal policy if policy_stable is True
  if(policy_stable):
    return policy, val_func
  else:
    return policy_improve(policy, discount_factor)

In [8]:
num_actions = 4
rows = 5
columns = 7
num_states = rows * columns
# Initial Uniform Random Policy
policy = np.ones([num_states, num_actions])/num_actions 
policy, val_func = policy_improve(policy = policy)
# Deterministic Policy returned
print(f'Determinsitic Policy:\n {policy}')
print(f'Value Function:\n {val_func.reshape(rows, columns)}')

Determinsitic Policy:
 [[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
Value Function:
 [[ 0.        0.       -1.       -1.999    -2.997001 -3.994004 -2.997001]
 [ 0.       -1.       -1.999    -2.997001 -3.994004 -2.997001 -1.999   ]
 [-1.       -1.999    -2.997001 -3.994004 -2.997001 -1.999    -1.      ]
 [-1.999    -2.997001 -3.994004 -2.997001 -1.999    -1.        0.      ]
 [-2.997001 -3.994004 -2.997001 -1.999    -1.        0.        0.      ]]
