In [1]:
import numpy as np
from GridWorld import env

In [2]:
def value_iter(policy, discount_factor = 0.99, theta = 0000000.1):
    # Value function initialized to 0 for all states
    val_func = np.zeros(num_states)
    while True:
        delta = 0
        # For each state in the state-space
        for curr_state in range(num_states):
            A = np.zeros(num_actions)
            # Find the values for all actions from curr_state
            for action in range(num_actions):
                prob, next_state, reward, isdone = env(curr_state, action, rows, columns)
                A[action] = prob * (reward + discount_factor * val_func[next_state])
            best_action = np.argmax(A)
            # Maximum value from all possible actions
            new_val = np.max(A)
            # Update the policy to be Greedy
            policy[curr_state] = np.eye(num_actions)[best_action]
            # Find the change in value for the curr_state
            delta = max(delta, np.abs(new_val - val_func[curr_state]))
            # Update value for the curr_state
            val_func[curr_state] = new_val
        # Check if change in value is lesser than theta
        if delta < theta:
            break
    return policy, val_func

In [5]:
num_actions = 4
rows = 4
columns = 6
num_states = rows * columns
# Initial Uniform Random Policy
policy = np.ones([num_states, num_actions])/num_actions 
policy, val_func = value_iter(policy = policy)
# Deterministic Policy returned
print(f'Determinsitic Policy: {policy}')
print(f'Value Function: {val_func.reshape(rows, columns)}')

Determinsitic Policy: [[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
Value Function: [[ 0.      0.     -1.     -1.99   -2.9701 -1.99  ]
 [ 0.     -1.     -1.99   -2.9701 -1.99   -1.    ]
 [-1.     -1.99   -2.9701 -1.99   -1.      0.    ]
 [-1.99   -2.9701 -1.99   -1.      0.      0.    ]]
